CREATE DATABASE IF NOT EXISTS `m001p596`;
USE `m001p596`;

DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
  id INT NOT NULL AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL,
  PRIMARY KEY(id)
) ENGINE=INNODB;

DROP TABLE IF EXISTS `post`;
CREATE TABLE `post` (
  id INT NOT NULL AUTO_INCREMENT,
  content TEXT NOT NULL,
  user_id INT NOT NULL,
  PRIMARY KEY(id)
) ENGINE=INNODB;

